# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Turn_plugin
                                 A QGIS plugin
 This plugin for QGIS allows user to turn group of vector objects around geometric center.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-04-06
        copyright            : (C) 2022 by Fadeev Alex
        email                : fadeew.alex@mail.ru
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Turn_plugin class from file Turn_plugin.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Turn_plugin import Turn_plugin
    return Turn_plugin(iface)
